---
- hosts: vm2[0]  #     hosts: vm[1:] vm[0]
  gather_facts: False
  become: True
  user: max

  roles:
    - install_python
    - { role: add_rsa_key, user: max, path_to_rsa: '/home/mmstepanov/.ssh/id_rsa.pub'}  #default user and path at vars
    - install_postgres
    - set_master
