---
- hosts: vm2[1:]  
  gather_facts: False
  become: True

  roles:
    - install_python
    - { role: add_rsa_key, user: max, path_to_rsa: '/home/mmstepanov/.ssh/id_rsa.pub'}  #default user and path at vars
    - install_postgres
    - set_follower
